version: "3"
services:
  client:
    image: vektor-client
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  server:
    image: vektor-api-server
    ports:
      - "8000:8000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
network:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
